name: Taller CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Simular construcción
        run: |
          echo "Construyendo el proyecto..."
          mkdir -p build
          cp index.html build/
          echo "Archivos construidos."

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Simular pruebas Linting
        run: |
          echo "Ejecutando pruebas..."
          grep -q "Rock" index.html
          echo "Linting OK."

      - name: Simular pruebas Unit Test
        run: |
          echo "Ejecutando pruebas de unidad..."
          grep -q "EventFlow" index.html
          echo "Unit test OK."

      - name: Despliegue simulado
        run: echo "¡Pruebas exitosas! Listo para desplegar."
